trigger:
  - main
pool:
  vmImage: ubuntu-latest

# jobs:
#   - job: install
#     pool:
#       vmImage: 'Ubuntu 16.04'
#     steps:
#     - bash: npm install
#       displayName: NPM Install Dependencies
#       condition: ne(variables['CacheRestored'], 'true')
#     - bash: ng lint
#       displayName: Run Angular linting
# - task: RestoreAndSaveCache@1
#   inputs:
#     keyfile: '**/package-lock.json, !**/node_modules/**/package-lock.json, !**/.*/**/package-lock.json'
#     targetfolder: '**/node_modules, !**/node_modules/**/node_modules'
#     vstsFeed: '106881c5-1e85-4e16-a467-be2702084631'
#     platformIndependent: true
steps:
  # - task: RestoreAndSaveCache@1
  #   inputs:
  #     keyfile: '**/package-lock.json, !**/node_modules/**/package-lock.json, !**/.*/**/package-lock.json'
  #     targetfolder: '**/node_modules, !**/node_modules/**/node_modules'
  #     vstsFeed: '106881c5-1e85-4e16-a467-be2702084631'
  #     platformIndependent: true
  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | package-lock.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
      path: $(Pipeline.Workspace)/.npm
    displayName: Cache NPM packages
  - script: | 
      npm ci
      echo $(Pipeline.Workspace)
    displayName: NPM Install Dependencies
    # condition: ne(variables['CacheRestored'], 'true')
  - script: npm run lint
    displayName: Lint
  - script: npm run test:ci
    displayName: Unit Tests
  - script: npm run build
    displayName: Build
